/**
 * Node-RED flow generation and Prometheus metrics.
 *
 * Node-RED is where most people actually wire IoT together, and hand-building a
 * flow for a dozen sensors is tedious and error-prone. This emits a complete,
 * importable flow from the same config the library already has — MQTT inputs,
 * threshold checks, a dashboard and an alert path — so a user goes from a
 * SmartPlant config to a working visual automation in one paste.
 */

import { METRICS } from '../sensors/driver.js'
import { DEFAULT_RANGES } from '../memory/context.js'

let nodeCounter = 0

/** Node-RED ids are opaque strings; any stable unique value works. */
function nodeId( prefix = 'sp' ) {

	nodeCounter++
	return `${prefix}${Date.now().toString( 36 )}${nodeCounter.toString( 36 )}`

}

/**
 * Build an importable Node-RED flow.
 *
 * @param   {object}   [config]            - Options.
 * @param   {string}   [config.plantName]  - Plant name, used in labels and topics.
 * @param   {string}   [config.broker]     - MQTT broker host.
 * @param   {number}   [config.port]       - MQTT broker port.
 * @param   {string}   [config.topicPrefix]- Base MQTT topic.
 * @param   {string[]} [config.metrics]    - Metrics to wire up.
 * @param   {object}   [config.ranges]     - Comfort ranges per metric.
 * @returns {object[]}                     Flow nodes, ready to import.
 */
export function generateFlow( config = {} ) {

	const plantName   = config.plantName || 'Plant'
	const slug        = plantName.toLowerCase().replace( /[^a-z0-9]+/g, '-' )
	const topicPrefix = config.topicPrefix || `smartplant/${slug}`
	const metrics     = config.metrics || [ 'temperature', 'humidity', 'soil', 'light' ]
	const ranges      = {
		...DEFAULT_RANGES,
		...config.ranges,
	}

	const tabId    = nodeId( 'tab' )
	const brokerId = nodeId( 'broker' )
	const uiTabId  = nodeId( 'uitab' )
	const uiGroupId= nodeId( 'uigroup' )

	const nodes = [
		{
			id    : tabId,
			type  : 'tab',
			label : `SmartPlant — ${plantName}`,
			info  : `Generated by SmartPlant.\n\nSubscribes to ${topicPrefix}/# and raises alerts when a metric leaves its comfort band.`,
			disabled : false,
		},
		{
			id       : brokerId,
			type     : 'mqtt-broker',
			name     : 'SmartPlant broker',
			broker   : config.broker || 'localhost',
			port     : String( config.port || 1883 ),
			clientid : '',
			autoConnect : true,
			keepalive: '60',
			cleansession : true,
		},
		{
			id    : uiTabId,
			type  : 'ui_tab',
			name  : plantName,
			icon  : 'fa-leaf',
			order : 1,
		},
		{
			id    : uiGroupId,
			type  : 'ui_group',
			name  : 'Live readings',
			tab   : uiTabId,
			order : 1,
			width : '6',
		},
	]

	const alertJoinId = nodeId( 'alert' )
	let y = 80

	for ( const metric of metrics ) {

		const meta  = METRICS[ metric ] || {
			label : metric,
			unit : '',
		}
		const range = ranges[ metric ]

		const inId    = nodeId( 'in' )
		const funcId  = nodeId( 'fn' )
		const gaugeId = nodeId( 'gauge' )

		nodes.push( {
			id     : inId,
			type   : 'mqtt in',
			z      : tabId,
			name   : meta.label,
			topic  : `${topicPrefix}/${metric}`,
			qos    : '0',
			datatype : 'auto',
			broker : brokerId,
			x      : 140,
			y,
			wires  : [ [ funcId, gaugeId ] ],
		} )

		// A function node rather than a switch: it carries the range into the
		// message so downstream nodes and the dashboard can show the band, and
		// keeps the whole rule visible in one place when a user edits the flow.
		nodes.push( {
			id   : funcId,
			type : 'function',
			z    : tabId,
			name : `check ${metric}`,
			func : [
				'const value = Number(msg.payload);',
				'if (!Number.isFinite(value)) return null;',
				`const range = { min: ${range?.min ?? 0}, max: ${range?.max ?? 100} };`,
				`msg.metric = ${JSON.stringify( metric )};`,
				'msg.range = range;',
				'if (value < range.min) { msg.state = "low"; }',
				'else if (value > range.max) { msg.state = "high"; }',
				'else { return null; }',
				`msg.payload = \`${plantName}: ${meta.label} \${msg.state} (\${value}${meta.unit}, ideal \${range.min}-\${range.max}${meta.unit})\`;`,
				'return msg;',
			].join( '\n' ),
			outputs : 1,
			x       : 380,
			y,
			wires   : [ [ alertJoinId ] ],
		} )

		nodes.push( {
			id      : gaugeId,
			type    : 'ui_gauge',
			z       : tabId,
			group   : uiGroupId,
			order   : metrics.indexOf( metric ) + 1,
			label   : meta.label,
			format  : `{{value}} ${meta.unit}`,
			min     : String( ( range?.min ?? 0 ) - ( range ? ( range.max - range.min ) : 20 ) ),
			max     : String( ( range?.max ?? 100 ) + ( range ? ( range.max - range.min ) : 20 ) ),
			colors  : [ '#ca3838', '#98d047', '#ca3838' ],
			x       : 380,
			y       : y + 40,
			wires   : [],
		} )

		y += 100

	}

	nodes.push( {
		id      : alertJoinId,
		type    : 'debug',
		z       : tabId,
		name    : 'alerts',
		active  : true,
		console : true,
		complete: 'payload',
		x       : 640,
		y       : 80,
		wires   : [],
	} )

	return nodes

}

/**
 * Node-RED subflow that calls back into a SmartPlant HTTP endpoint, for users
 * who want the visual layer to trigger the library's AI rather than reimplement
 * the logic in function nodes.
 *
 * @param   {object}   [config]     - Options.
 * @param   {string}   [config.url] - SmartPlant HTTP endpoint.
 * @returns {object[]}              Flow nodes.
 */
export function generateAiFlow( config = {} ) {

	const tabId = nodeId( 'tab' )
	const reqId = nodeId( 'req' )
	const inId  = nodeId( 'inj' )
	const outId = nodeId( 'dbg' )

	return [
		{
			id    : tabId,
			type  : 'tab',
			label : 'SmartPlant — ask the plant',
		},
		{
			id      : inId,
			type    : 'inject',
			z       : tabId,
			name    : 'every 6 hours',
			repeat  : String( 6 * 3600 ),
			topic   : '',
			payload : '{"question":"How are you feeling?"}',
			payloadType : 'json',
			x       : 150,
			y       : 80,
			wires   : [ [ reqId ] ],
		},
		{
			id     : reqId,
			type   : 'http request',
			z      : tabId,
			name   : 'SmartPlant',
			method : 'POST',
			ret    : 'obj',
			url    : config.url || 'http://localhost:3000/ask',
			x      : 360,
			y      : 80,
			wires  : [ [ outId ] ],
		},
		{
			id     : outId,
			type   : 'debug',
			z      : tabId,
			name   : 'answer',
			active : true,
			complete : 'payload',
			x       : 560,
			y       : 80,
			wires   : [],
		},
	]

}

/**
 * Render the current state in Prometheus text exposition format.
 *
 * Serve this from any HTTP endpoint and Grafana, Alertmanager and the rest of
 * that stack work with no further integration.
 *
 * @param   {object} plant     - A `SmartPlant` instance.
 * @param   {object} [reading] - Reading override.
 * @returns {string}           Prometheus metrics.
 */
export function prometheusMetrics( plant, reading ) {

	const current = reading || plant.memory.lastReading || {}
	const name    = plant.memory.plant.name || 'unnamed'
	const species = plant.memory.plant.species || 'unknown'
	const labels  = `plant="${escapeLabel( name )}",species="${escapeLabel( species )}"`

	const lines = []

	for ( const [ metric, meta ] of Object.entries( METRICS ) ) {

		if ( !Number.isFinite( current[ metric ] ) ) continue
		lines.push(
			`# HELP smartplant_${metric} ${meta.label}${meta.unit ? ` in ${meta.unit}` : ''}`,
			`# TYPE smartplant_${metric} gauge`,
			`smartplant_${metric}{${labels}} ${current[ metric ]}`,
		)

	}

	lines.push(
		'# HELP smartplant_wellbeing Overall wellbeing 0-100',
		'# TYPE smartplant_wellbeing gauge',
		`smartplant_wellbeing{${labels}} ${plant.happiness( current )}`,
		'# HELP smartplant_readings_total Readings stored in memory',
		'# TYPE smartplant_readings_total gauge',
		`smartplant_readings_total{${labels}} ${plant.memory.data.readings.length}`,
		'# HELP smartplant_ai_requests_total AI requests issued',
		'# TYPE smartplant_ai_requests_total counter',
		`smartplant_ai_requests_total{${labels}} ${plant.ai.stats.requests}`,
		'# HELP smartplant_days_since_water Days since the last recorded watering',
		'# TYPE smartplant_days_since_water gauge',
		`smartplant_days_since_water{${labels}} ${plant.memory.daysSince( 'water' ) ?? -1}`,
	)

	return lines.join( '\n' ) + '\n'

}

function escapeLabel( s ) {

	return String( s ).replace( /\\/g, '\\\\' ).replace( /"/g, '\\"' ).replace( /\n/g, ' ' )

}
