/**
 * SmartPlant as an OpenClaw plugin.
 *
 * The other direction from `OpenClawBrain`: instead of SmartPlant driving the
 * Gateway, the Gateway's own agent gets the plant's tools. Same control surface,
 * same safety gates — but now reachable from whatever channel OpenClaw is
 * connected to, so the plant can be operated from a phone.
 */

import { SmartPlantError } from '../../core/errors.js'
import { PLANT_TOOLS, selectTools } from './tools.js'

/**
 * Bind the tools to a plant, ready to call.
 *
 * @param   {object}   plant           - A `SmartPlant` instance.
 * @param   {object}   [opts]          - Options.
 * @param   {string[]} [opts.only]     - Restrict to these tool names.
 * @param   {boolean}  [opts.readOnly] - Withhold every acting tool.
 * @returns {object[]}                 `[{name, description, parameters, acts, execute}]`.
 */
export function createToolHandlers( plant, opts = {} ) {

	if ( !plant ) throw new SmartPlantError( 'createToolHandlers needs a plant.', 'CONFIG_ERROR' )

	return selectTools( opts ).map( tool => ( {
		name        : tool.name,
		description : tool.description,
		parameters  : tool.parameters,
		acts        : tool.acts,
		async execute( params = {} ) {

			try {

				const result = await tool.handler( plant, params )
				return {
					ok : result?.applied !== false && !result?.refused,
					...result,
				}

			}
			catch ( err ) {

				// A tool that throws mid-conversation is a bad experience; return
				// the failure as data so the model can explain it.
				return {
					ok : false,
					error : err.message,
				}

			}

		},
	} ) )

}

/**
 * Generate a complete OpenClaw plugin package.
 *
 * Emits the three files the plugin SDK expects: a `package.json` carrying the
 * `openclaw` block, an `openclaw.plugin.json` manifest declaring the tool
 * contracts, and an entry point using `definePluginEntry` + `api.registerTool`.
 *
 * @param   {object}   [config]             - Options.
 * @param   {string}   [config.id]          - Plugin id.
 * @param   {string}   [config.name]        - Display name.
 * @param   {string}   [config.packageName] - npm package name.
 * @param   {object}   [config.plant]       - Plant config baked into the plugin.
 * @param   {string[]} [config.tools]       - Restrict to these tools.
 * @param   {boolean}  [config.readOnly]    - Expose only reading tools.
 * @param   {string}   [config.pluginApi]   - Required plugin API range.
 * @returns {object}                        Path → file contents.
 */
export function generatePlugin( config = {} ) {

	const id          = config.id || 'smartplant'
	const name        = config.name || 'SmartPlant'
	const packageName = config.packageName || '@smartplant/openclaw-plugin'
	const pluginApi   = config.pluginApi || '>=2026.3.24-beta.2'

	const tools = selectTools( {
		only : config.tools,
		readOnly : config.readOnly,
	} )

	const plantConfig = {
		name    : 'Ivy',
		species : 'Monstera deliciosa',
		sensor  : 'mock',
		ai      : { provider : 'mock' },
		memory  : { path : './smartplant.json' },
		...config.plant,
	}

	const pkg = {
		name    : packageName,
		version : '1.0.0',
		description : 'Operate your plants from any OpenClaw channel.',
		type    : 'module',
		peerDependencies : { openclaw : pluginApi },
		dependencies     : { smartplant : '^3.0.5' },
		openclaw : {
			extensions : [ './index.js' ],
			compat     : { pluginApi },
		},
		license : 'MIT',
	}

	const manifest = {
		id,
		name,
		description : 'Sensors, electrophysiology, spectral probing, diagnosis and care for your plants.',
		contracts   : { tools : tools.map( t => t.name ) },
		activation  : { onStartup : true },
	}

	const entry = `/**
 * ${name} — OpenClaw plugin.
 *
 * Generated by SmartPlant. Registers ${tools.length} tool(s) so the assistant can
 * read, diagnose and care for your plants from any connected channel.
 *
 * Acting tools go through SmartPlant's own safety layers — the evidence ledger,
 * the safety supervisor, the spectral interlocks. A refusal comes back as a
 * tool result explaining why, not as an error.
 *
 * Edit PLANT_CONFIG below to point at your real sensor.
 */

import { definePluginEntry } from 'openclaw/plugin'
import { Type } from '@sinclair/typebox'
import { createPlant } from 'smartplant'
import { createToolHandlers } from 'smartplant/integrations/openclaw'

const PLANT_CONFIG = ${JSON.stringify( plantConfig, null, 2 )}

// One shared plant across the process: the memory file, the sensor connection
// and the lamp should be opened once, not once per tool call.
let plantPromise = null
const getPlant = () => {

	if ( !plantPromise ) plantPromise = createPlant( PLANT_CONFIG )
	return plantPromise

}

export default definePluginEntry( {
	id          : ${JSON.stringify( id )},
	name        : ${JSON.stringify( name )},
	description : 'Sensors, electrophysiology, spectral probing, diagnosis and care for your plants.',

	register( api ) {

${tools.map( t => `		api.registerTool( {
			name        : ${JSON.stringify( t.name )},
			description : ${JSON.stringify( t.description )},
			parameters  : ${typeboxFor( t.parameters )},
			async execute( _id, params ) {

				const plant = await getPlant()
				const [ tool ] = createToolHandlers( plant, { only : [ ${JSON.stringify( t.name )} ] } )
				const result = await tool.execute( params || {} )

				return {
					content : [ { type : 'text', text : JSON.stringify( result, null, 2 ) } ],
					details : result,
				}

			},
		} )` ).join( '\n\n' )}

	},
} )
`

	const readAndAct = {
		read : tools.filter( t => !t.acts ),
		act  : tools.filter( t => t.acts ),
	}

	const readme = `# ${name} — OpenClaw plugin

Operate your plants from WhatsApp, Telegram, Slack, Discord — any channel your
OpenClaw Gateway is connected to.

## Install

\`\`\`bash
npm install ${packageName}
\`\`\`

Then register it with your Gateway and restart it.

## Configure

Edit \`PLANT_CONFIG\` in \`index.js\`:

\`\`\`js
const PLANT_CONFIG = {
  name    : 'Ivy',
  species : 'Monstera deliciosa',
  sensor  : { driver: 'serial', path: '/dev/ttyUSB0' },   // your real sensor
  memory  : { path: './smartplant.json' },
}
\`\`\`

Not sure what hardware you have? Ask the assistant to run \`plant_hardware\`.

## Tools

### Reading — always safe

${readAndAct.read.map( t => `- **${t.name}** — ${t.description}` ).join( '\n' )}

${readAndAct.act.length ? `### Acting — gated by SmartPlant's safety layers

${readAndAct.act.map( t => `- **${t.name}** — ${t.description}` ).join( '\n' )}

An acting tool can be refused. The refusal comes back with its reason, so the
assistant can explain it rather than failing silently.` : '_This plugin was generated read-only: no acting tools are exposed._'}

## Try it

> "How's Ivy doing?"
> "Run a spectral scan and tell me if she's thirsty or hungry"
> "I just watered her, 200ml"
> "Something's wrong with the plant, investigate"
`

	return {
		'package.json'         : JSON.stringify( pkg, null, 2 ) + '\n',
		'openclaw.plugin.json' : JSON.stringify( manifest, null, 2 ) + '\n',
		'index.js'             : entry,
		'README.md'            : readme,
	}

}

/** Render a JSON-Schema-ish parameter block as a TypeBox expression. */
function typeboxFor( schema ) {

	const props = schema?.properties || {}
	const required = schema?.required || []

	if ( !Object.keys( props ).length ) return 'Type.Object( {} )'

	const fields = Object.entries( props ).map( ( [ key, def ] ) => {

		const base = def.type === 'number'
			? 'Type.Number()'
			: def.type === 'boolean' ? 'Type.Boolean()' : 'Type.String()'

		const withDesc = def.description
			? base.replace( ')', `{ description: ${JSON.stringify( def.description )} } )` )
			: base

		return `\t\t\t\t${key} : ${required.includes( key ) ? withDesc : `Type.Optional( ${withDesc} )`}`

	} )

	return `Type.Object( {\n${fields.join( ',\n' )},\n\t\t\t} )`

}

export { PLANT_TOOLS }
